# Generated by Django 3.0.8 on 2020-07-17 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0002_auto_20200717_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_challenges_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
