# Generated by Django 3.0.8 on 2020-07-20 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_question_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tests_for_question',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
