# Generated by Django 3.0.8 on 2020-07-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('question', '0003_auto_20200714_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='program',
            field=models.ManyToManyField(related_name='question_program', to='program.Program'),
        ),
    ]
